{
  "hash": "d3f621864565447340f4e075389d951e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Transit Prediction Model- Technical Appendix\"\nsubtitle: \"MUSA 5080 - Public Policy Analytics\"\nauthor: \"Indrajeet Chavan, Wil Rantala, Alajandro Duque, Umair Saad\"\ndate: \"May 8, 2026\"\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n# Table of Contents\n\n1.  Introduction\n2.  Data cleaning and exploration\n3.  Creating variables and geographical features\n4.  Model Creations and Validations\n5.  Model Results\n\n# Introduction\n\nFor this assignment, we were challenged to build a predictive model that Philadelphia city officials would want to employ, using only the techniques we’ve covered this semester in Public Policy Analytics.\n\n**The project involves two key deliverables:**\n\n-   A Shark Tank style presentation to a panel of judges who grill each team on their methods, assumptions, and recommendations\n\n-   A comprehensive technical appendix that details each step of our data exploration, variable creation, manipulations, and model creation, as well as the evaluation of our models\n\nWe were provided with a handful of datasets to select from: evictions, property tax delinquency, building inspections, and SEPTA ridership. Our team ultimately decided to go with SEPTA bus stop summary data to predict ridership, as our team members have interests in transit data and how ridership is connected to other urban patterns.\n\n**What will our model do?**\n\n-   Our model will predict SEPTA bus ridership in Philadelphia at the level of 1000x1000ft grid cells. Ridership will be an aggregated count of boardings and alightings at bus stops (ons and off) in each cell.\n\n**How will it do it?**\n\n-   We will use demographic characteristics, spatial features like nearby jobs and other transit infrastructure, and other open Philadelphia data as predictors (independent variables) in various models to create the best predictive model we can. - Methods will include OLS regression, Spatial Lag, Poisson, and Negative Binomial.\n\n**How do we hope it could be used?**\n\nWe hope our model’s ability to predict ridership across Philadelphia based on spatial features and characteristics of each cell could be used to help SEPTA predict which parts of the city would have high ridership if supplied more bus lines/stops, and find places where they should be more inclined to invest in. SEPTA has highly limited funding, so they have to be as effective as possible with each dollar they put into their transit service. By using data as another layer of selecting places to invest in, we hope this model could help them to most effectively serve the population of Philadelphia with each dollar in their budget.\n\n**Worries about malicious use of the model to justify disinvestment**\n\n-   In our shark tank presentation, one of the panel members put forward a concern that policymakers and those looking to cut SEPTA’s funding and service could use this model to justify cutting in low-ridership-predicted areas. This poses a major equity concern.\n\n-   We understand this concern, and we ourselves are worried about it too. To make sure this model has safeguards against such uses, we will be upfront with our argument that this could and should not be used in such a way.\n\n-   Cutting service to low-ridership areas can actually increase costs system-wide. Those riders will shift to paratransit, social services, or emergency services that cost far more per trip.\n\n-   If somebody attempts to use results from this model to cut low-ridership areas, SEPTA and other transit advocates should make this very clear.\n\n-   Low ridership in an area is often caused by poor service. A model trained on observed ridership will tend to reproduce that pattern.\n\n-   Instead of looking for places where ridership is low as potential places to cut, areas where predicted demand from demographics significantly exceeds observed riderships are candidates for expansion.\n\n-   Cells where model-predicted ridership significantly exceeds observed ridership are flagged as underserved.\n\n**What data will we use?**\n\n-   SEPTA bus stop summaries from Fall 2022, Fall ‘23, Fall 24’, and Fall ‘25.\n\n-   2023 5-year ACS data at the census tract level. The ACS variables we’ve gathered:\n\n-   Total population (to derive population density of cells)\n\n-   Total households\n\n-   Households without vehicles\n\n-   Median income\n\n-   Poverty counts and denoms\n\n-   \\% White, Black, Hispanic, and Asian\n\n-   SEPTA regional rail and ‘El’ rail stops.\n\n-   LODES 2023 employment statistics at the block group level\n\n-   Local roads shapemap (places without roads can’t have buses)\n\n-   Roads will be helpful to future proof the model in case more road infrastructure gets built in the future.\n\n**On/off data?**\n\n-   In our model, we decided to aggregate on/off data to total ridership to act as our dependent variable.\n-   We decided against differentiated ons and offs at bus stops under the assumption that at a given time of day, a cell with high ons, will have similar levels of offs at another time of day (assumption that popular trip destinations will also be popular trip origin points).\n-   We acknowledge this assumption is stronger in some parts of the city than others – dense employment centers like Center City may see systematically higher offs in the morning peak and higher ons in the evening. However, since our model operates at the cell level and across all hours of the day, we expect total ridership to remain a reasonable proxy for overall transit activity in a given area.\n\n**Why 2022-2025 data? Why not earlier data too?**\n\n-   Covid-19 dealt a massive blow to ridership on transit systems across the US. Most cities have only just achieved ridership recovery of 75% of their ridership before the pandemic.\n-   To avoid any major pattern disruptions that occurred during the pandemic, we chose to exclude 2020 and 2021 ridership observations.\n\n**Why we’re not doing a time lag**\n\nChanges in stops/routes in cells over the years will change ridership drastically. If we predict the ridership from last year when a cell didn’t have a line going through it, but it does now, then ridership will have risen at that location, but we can’t assume it’ll keep increasing. That’s the issue with the time lag in this scenario.\n\n**Model Uncertainty/Limitations**\n\nAs with any predictive model, our estimates carry uncertainty – particularly in grid cells with sparse data, limited road access, or no existing bus infrastructure. Predicted ridership values should be interpreted as probabilistic estimates of underlying demand rather than precise forecasts, and decisions based on this model should weigh that uncertainty accordingly.\n\n**What models we’ll use:**\n\n-   OLS regression\n-   Negative binomial\n-   We are not doing a spatial lag model\n-   We are not doing a Poisson model\n\nA negative binomial model will be our better model since it is designed for count data, which is what our dependent variable, ridership, is. Negative binomial will especially be more effective since it accounts for overdispersion in the data – something that Poisson cannot do. OLS regression will be the first model we create since it’s simple and can act as a baseline to understand our variables’ relationships with ridership in a simple linear manner.\n\nWith the spatial lag model, there are concerns about predicting using lagged ridership. The lag term means the model is predicting recursively, which gets messy especially for policy use. If a cell’s predicted ridership leans on its neighbors’ actual ridership, then under-served pockets surrounded by under-served pockets will get predicted as low-ridership, masking exactly the latent demand a transit agency would want to spot. To absorb the spatial dependence of ridership, we included spatially-aware predictors like distance to rail, jobs within a half-mile, demographic composition, which absorb most of the spatial structure without the prediction tradeoffs.\n\n**Model validation**\n\nWe’ll do leave-one-out cross validation (LOOCV) on our models. Because our dataset consists of a finite number of grid cells across Philadelphia, LOOCV is computationally feasible and gives us the most rigorous possible test of how well our model predicts ridership in cells it has not been trained on. This simulates real-world deployment of the model where it would be asked to predict demand in new or currently unserved areas.\n\n# Let's code!\n\n## Phase 1: Data Cleaning and Exploratory Data Analysis\n\n#### Step 1: Load Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Clearing previous data\nrm(list=ls())\n\n#Loading the libraries\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(tidycensus)\nlibrary(tigris)\nlibrary(lubridate)\nlibrary(janitor)\nlibrary(knitr)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(janitor)\nlibrary(patchwork)\nlibrary(lehdr)\nlibrary(spdep)\nlibrary(caret)\n\noptions(tigris_use_cache = TRUE)\n```\n:::\n\n\n#### Step 2: Load & Inspect Bus Ridership\n\n\n\n#### Step 3: Clean + Create Target Variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbus_rider <- bus_rider %>%\n  mutate(\n    week_on = as.numeric(week_on),\n    sat_on  = as.numeric(sat_on),\n    sun_on  = as.numeric(sun_on),\n    total_riders = week_on + sat_on + sun_on\n  ) %>%\n  filter(!is.na(x), !is.na(y), total_riders > 0)\n\n# Convert to sf\nbus_rider_sf <- bus_rider %>%\n  mutate(\n    lat = as.numeric(lat),\n    lon  = as.numeric(lon)\n    ) %>%\n  st_as_sf(coords = c(\"lon\",\"lat\"), crs = 4326) %>%\n  st_transform(2272)\n\nggplot(bus_rider_sf) +\n  geom_sf(color = \"blue\", size = 1) +\n  theme_minimal() +\n  labs(title = \"Bus Stops\")\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/clean data-1.png){width=672}\n:::\n:::\n\n\n#### Step 4: Create 1000 × 1000 ft Grid (fishnet)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Loading the Philly boundary\nphiladelphia <- get_acs(\n  geography = \"county\",\n  variables = \"B01003_001\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  geometry = TRUE,\n  year = 2023\n) %>%\n  st_transform(2272)\n\n# Creating the 1000 x 1000 ft grid\nphilly_grid <- st_make_grid(philadelphia, cellsize = 1000, square = TRUE) %>%\n  st_sf() %>%\n  mutate(cell_id = row_number())\n\n# Clip the grid to the city boundaries\nphilly_grid <- philly_grid[philadelphia, ]\n\n# 3. Pull census tracts with raw counts\nacs_vars <- c(\n  total_pop     = \"B01003_001\",\n  total_hh      = \"B08201_001\",\n  no_vehicle_hh = \"B08201_002\",\n  median_income = \"B19013_001\",\n  poverty_denom = \"B17001_001\",\n  poverty_count = \"B17001_002\",\n  white         = \"B03002_003\",\n  black         = \"B03002_004\",\n  hispanic      = \"B03002_012\",\n  asian         = \"B03002_006\"\n)\n\ntracts <- get_acs(\n  geography = \"tract\",\n  variables = acs_vars,\n  state = \"PA\",\n  county = \"Philadelphia\",\n  geometry = TRUE,\n  year = 2024,\n  output = \"wide\"\n) %>%\n  st_transform(2272)\n```\n:::\n\n\n#### Step 5: Aggregate census data to the grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Interpolate counts onto grid and keep geometry so we can join spatially\ngrid_counts <- st_interpolate_aw(\n  tracts %>% select(total_popE, poverty_countE, poverty_denomE,\n                    no_vehicle_hhE, total_hhE,\n                    whiteE, blackE, hispanicE, asianE, geometry),\n  philly_grid,\n  extensive = TRUE\n)\n\n# Interpolate income onto grid and keep geometry so we can join spatially\ngrid_income <- st_interpolate_aw(\n  tracts %>% select(median_incomeE, geometry),\n  philly_grid,\n  extensive = FALSE\n) %>%\n  rename(median_income = median_incomeE)\n\n# Spatial join back to grid (avoids row_number() misalignment)\nphilly_grid_census <- philly_grid %>%\n  st_join(grid_counts %>% select(-geometry), join = st_equals) %>%\n  st_join(grid_income  %>% select(median_income, geometry), join = st_equals) %>%\n  mutate(\n    cell_area_km2  = (1000 * 0.3048)^2 / 1e6,  # This is to convert it to km^2 from feet\n    pop_density    = total_popE / cell_area_km2,\n    pct_no_vehicle = no_vehicle_hhE / total_hhE,\n    pct_poverty    = poverty_countE / poverty_denomE,\n    pct_white      = whiteE / total_popE,\n    pct_black      = blackE / total_popE,\n    pct_hispanic   = hispanicE / total_popE,\n    pct_asian      = asianE / total_popE,\n  )\n```\n:::\n\n\n#### Step 6: Treating all the void cells and NAs\n\nWe get some NAs for median_income, let's get neighboring cells' incomes and average them for those. On one pass of this function, there were still some NAs because the cells were using adjacent cells' NAs to try to fill in median income. For that reason, we're doing a for loop to repeat the function until there aren't any NAs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter out any cells that have 0 population\nphilly_grid_census <- philly_grid_census %>%\n  filter(!is.na(total_popE), total_popE > 0)\n\n# Fill any cells that have NA in median_income\n\nfill_na_from_neighbors_iter <- function(grid, col, max_iter = 10) {\n  vals <- grid[[col]]\n  nb <- st_touches(grid)\n  \n  for (i in seq_len(max_iter)) {\n    if (!any(is.na(vals))) break  # stop early if no NAs remain\n    \n    vals <- sapply(seq_along(vals), function(i) {\n      if (!is.na(vals[i])) return(vals[i])\n      neighbor_vals <- vals[nb[[i]]]\n      neighbor_vals <- neighbor_vals[!is.na(neighbor_vals)]\n      if (length(neighbor_vals) == 0) return(NA)\n      mean(neighbor_vals)\n    })\n  }\n  vals\n}\n\n#Filter NAs from the cells\nphilly_grid_census <- philly_grid_census %>%\n  mutate(median_income = fill_na_from_neighbors_iter(., \"median_income\")) # This still spits out a few NAs. Most likely, it's beacause some of the NA cells had NAs neighboring them.\n```\n:::\n\n\n#### Step 7: How does the census data look once aggregated to the grid?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualizing the census grid\nd1 <- ggplot(philly_grid_census) +\n  aes(fill = pop_density) +\n  geom_sf(color = NA) +\n  scale_fill_viridis_c(option = \"magma\", name = \"Pop/km²\") +\n  labs(title = \"Population Density by Grid Cell\") +\n  theme_void()\n\nd1\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/Mapping the census data as grid-1.png){width=672}\n:::\n:::\n\n\n#### Step 8: How about we assign the bus stops and data to the cells?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join to assign each bus stop to a grid cell\nbus_rider_sf <- bus_rider_sf %>%\n  select(-x, -y) \n\nbus_with_grid <- st_join(bus_rider_sf, philly_grid, join = st_intersects)\n\n# Clip to city boundary\nbus_with_grid <- bus_with_grid[philadelphia, ]\n  \n#Visualising the bus with grid with the grid for Philadelphia County to check if data is aligning for aggregation\nggplot() +\n  geom_sf(data = philly_grid, fill = NA, color = \"grey\") +\n  geom_sf(data = bus_with_grid, color = \"red\", size = 1) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/Assigning bus stops to cells-1.png){width=672}\n:::\n:::\n\n\n#### Step 9: Finally, its time to aggregate the bus data to the grid we have created!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating co-ordintes for the bus stops\nbus_with_grid <- bus_with_grid %>%\n  mutate(\n    coords = st_coordinates(geometry),\n    stop_id = paste0(round(coords[,1], 2), \"_\", round(coords[,2], 2))\n  )\n\n#Visualising how these bus stops look in a grid\nggplot() +\n  geom_sf(data = bus_with_grid)+\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/Aggregating bus data to the grid-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Grouping the bus stops by cell id to aggregate\nbus_grid_summary <- bus_with_grid %>%\n  st_drop_geometry() %>%\n  group_by(cell_id) %>%\n  summarise(\n    total_riders = sum(total_riders, na.rm = TRUE),\n\n    # unique stops (based on coordinates)\n    unique_stops = n_distinct(stop_id),\n\n    # unique routes in that grid cell\n    unique_routes = n_distinct(route)\n  )\n```\n:::\n\n\n#### Step 10: Collecting all the bus, transit and census data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly_grid_final <- philly_grid_census %>%\n  left_join(bus_grid_summary, by = \"cell_id\") %>%\n  mutate(\n    total_riders = replace_na(total_riders, 0),\n    unique_stops   = replace_na(unique_stops, 0),\n    unique_routes   = replace_na(unique_routes, 0)\n  )\n```\n:::\n\n\n#### Step 11: Mapping the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let's visualize bus ridership, stops, and lines on the grid\n\np1 = ggplot(philly_grid_final) +\n  aes(fill = total_riders) +\n  geom_sf(color = NA) +\n  scale_fill_viridis_c(option = \"magma\", \n                       name = \"Bus Ridership\", \n                       limits = c(0, 10000),\n                       oob = scales::squish) +\n  labs(title = \"Bus Ridership by Cell\") +\n  theme_void()\n\np2 = ggplot(philly_grid_final) +\n  aes(fill = unique_stops) +\n  geom_sf(color = NA) +\n  scale_fill_viridis_c(option = \"magma\", \n                       name = \"Bus Stops\") +\n  labs(title = \"Bus Stops by Cell\") +\n  theme_void()\n\np3 = ggplot(philly_grid_final) +\n  aes(fill = unique_routes) +\n  geom_sf(color = NA) +\n  scale_fill_viridis_c(option = \"magma\", \n                       name = \"Bus Routes\",\n                       limits = c(0, 10),\n                       oob = scales::squish) +\n  labs(title = \"Number of Bus Routes that stop in each cell\") +\n  theme_void()\n\n# This prints the three maps together \np1 + p2 + p3 + plot_layout(ncol = 2)  # 2x2 grid (last slot empty)\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/Mapping riders, unique stops and unique routes each grid cell-1.png){width=672}\n:::\n:::\n\n\n### Data Bias\n\nHere we have bus ridership, stops, and routes in each cell mapped out together. The ridership and route maps are rather similar, which makes sense as ridership would peak in areas where multiple bus routes overlap or intercept.\n\nIt looks like we've got some pretty major outliers on our hands. In North Philly, there are two cells with 70k+ riders. These points are major bus transfer centers where 10+ routes intersect at the same spot. For our model, we're going to remove these points as their large values may sway the results and worsen our predictive power.\n\nLet's remove cells that have total riders greater than 40 thousand, as we are not looking to predict bus ridership at/from bus transfer centers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly_grid_final <- philly_grid_final %>%\n  filter(total_riders <= 25000)\n```\n:::\n\n\n#### Step 12: How about we add some more Spatial Data for Rails and Buses?\n\nLet's get a the locations of regional rail and Philly \"El\" stops to create a new predictor. We'll have a predictor of distance to nearest transit.\n\n\n\n#### Step 13: Clip SEPTA rail stops to the Philly boundary\n\nHey the data continues beyond the boundaries of Philly! Let's trim it down.\n\nThe full extent of the rail systems serve outside of Philadelphia County's boundaries. Let's make sure to clip it to the city\n\nNote: To see what they look like now that they've been clipped, go back to where we created p4 and p5 and just re-run the code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Clipping spatial data to Philadelphia Boundary\nel_rail <- el_rail[philadelphia, ]\nreg_rail <- reg_rail[philadelphia, ]\n\n# Rerunning the code to map them on top of our Philly Grid!\np4 = ggplot(reg_rail) +\n  geom_sf(data = philly_grid_final, fill = NA, color = \"grey\") +\n  geom_sf(color = \"blue\", size = 1) +\n  theme_void() +\n  labs(title = \"Regional Rail Stops\")\n\np5 = ggplot(el_rail) +\n  geom_sf(data = philly_grid_final, fill = NA, color = \"grey\") +\n  geom_sf(color = \"green\", size = 1) +\n  theme_void() +\n  labs(title = \"El Stops\")\n\np4 + p5\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/clip rail data to Philadelphia boundaries-1.png){width=672}\n:::\n:::\n\n\n#### Step 14: Creating Spatial Variables for our Model\n\nNow that we have the data, it's time to aggregate this data to the grid and create some predictors\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of each grid cell\ngrid_centroids <- st_centroid(philly_grid_final)\n\n# Distance to nearest regional rail station (points)\ndist_reg_rail <- st_distance(grid_centroids, reg_rail)  # matrix: cells x stations\nphilly_grid_final$dist_reg_rail_ft <- apply(dist_reg_rail, 1, min)\n\n# Distance to nearest El line (lines)\ndist_el <- st_distance(grid_centroids, el_rail)  # matrix: cells x line segments\nphilly_grid_final$dist_el_ft <- apply(dist_el, 1, min)\n\n# Check if it looks right on a map!\nd2 <- ggplot() +\n  geom_sf(data = philly_grid_final, aes(fill = dist_el_ft), color = NA) +\n  geom_sf(data = el_rail, color = \"green\", size = 1) +\n  scale_fill_viridis_c(option = \"magma\", name = \"Distance to El (ft)\") +\n  theme_void() +\n  labs(title = \"El Stops and Cell Distance to Nearest Station\")\n\nd2\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/create grid centroids and join spatial data to grid-1.png){width=672}\n:::\n:::\n\n\n#### Step 15: Employment Data\n\nUmm... What is still missing?? Oh right! This model needs some data for employment\n\nWe want to use the number of jobs within a half mile of each cell as a predictor for ridership.\n\nTo do this, we'll use LEHD LODES data at the block group level. Lastly, we will map this because what's the fun if we dont see the visualisation?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# API call to get the lodes data\nlodes<- grab_lodes(\n  state = \"pa\",\n  year = 2023,\n  lodes_type = \"wac\",\n  job_type = \"JT00\",\n  segment = \"S000\",\n  state_part = \"main\",\n  agg_geo = \"bg\"   #IMPORTANT\n)\n\nblock_groups <- block_groups(state = \"PA\", county = \"Philadelphia\", year = 2023) %>%\n  st_transform(2272)\n\nnames(lodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"year\"  \"state\" \"w_bg\"  \"C000\"  \"CA01\"  \"CA02\"  \"CA03\"  \"CE01\"  \"CE02\" \n[10] \"CE03\"  \"CNS01\" \"CNS02\" \"CNS03\" \"CNS04\" \"CNS05\" \"CNS06\" \"CNS07\" \"CNS08\"\n[19] \"CNS09\" \"CNS10\" \"CNS11\" \"CNS12\" \"CNS13\" \"CNS14\" \"CNS15\" \"CNS16\" \"CNS17\"\n[28] \"CNS18\" \"CNS19\" \"CNS20\" \"CR01\"  \"CR02\"  \"CR03\"  \"CR04\"  \"CR05\"  \"CR07\" \n[37] \"CT01\"  \"CT02\"  \"CD01\"  \"CD02\"  \"CD03\"  \"CD04\"  \"CS01\"  \"CS02\"  \"CFA01\"\n[46] \"CFA02\" \"CFA03\" \"CFA04\" \"CFA05\" \"CFS01\" \"CFS02\" \"CFS03\" \"CFS04\" \"CFS05\"\n```\n\n\n:::\n\n```{.r .cell-code}\njobs_sf <- block_groups %>%\n  left_join(lodes, by = c(\"GEOID\" = \"w_bg\")) %>%\n  filter(!is.na(C000))\n\n# Let's map it to make sure it looks ok\nggplot(jobs_sf) +\n  aes(fill = C000) +\n  geom_sf(color = NA) +\n  scale_fill_viridis_c(option = \"magma\", name = \"Total Jobs\", \n                       limits = c(0, 10000), \n                       oob = scales::squish) +\n  labs(title = \"Jobs by Block Group in Philadelphia\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/grabbing LEHD LODES data-1.png){width=672}\n:::\n:::\n\n\n#### Step 16: Half-mile buffer\n\nOk, looks like we've got accurate job counts by acs block groups!\n\nNow, let's create a half-mile buffer and summarize the \\# of jobs for each cell\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create half-mile buffers around each cell centroid\nbuffers <- st_buffer(grid_centroids, dist = 5280 * 0.5) %>%\n  select(cell_id, geometry)\n\n# Spatial join buffers to block groups, weighted by overlap area\njobs_interp <- st_interpolate_aw(\n  jobs_sf %>% select(C000, geometry),\n  buffers,\n  extensive = TRUE\n) %>%\n  st_drop_geometry() %>%\n  mutate(cell_id = buffers$cell_id) %>%\n  rename(jobs_half_mile = C000)\n\n# Join back to grid\nphilly_grid_final <- philly_grid_final %>%\n  left_join(jobs_interp, by = \"cell_id\")\n```\n:::\n\n\n#### Step 17: Map the results for the half-mile buffer\n\nOf course, let's map the results! Here's a map of jobs within a half mile of each cell\n\n\n::: {.cell}\n\n```{.r .cell-code}\np6 = ggplot(philly_grid_final) +\n  aes(fill = jobs_half_mile) +\n  geom_sf(color = NA) +\n  scale_fill_viridis_c(option = \"magma\", \n                       name = \"Jobs within a half-mile\", \n                       limits = c(0, 25000), \n                       oob = scales::squish) +\n  labs(\n    title = \"Jobs within a half-mile of each 1000x1000ft cell in Philadelphia\",\n    caption = \"Scale capped at 25,000 to highlight secondary job centers. Many cells exceed 100,000 jobs within a half-mile.\") +\n  theme_void()\n\np6\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/creating jobs map-1.png){width=672}\n:::\n:::\n\n\nClearly, jobs are highly concentrated downtown and in University City. Let's compare it to the bus ridership map to see if there's a visual similarity of patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 + p6\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/map ridership and jobs within a half-mile-1.png){width=672}\n:::\n:::\n\n\nThere's definitely a discernible similarity here!\n\nCity center and along Broad Street extending north and south have notable high ridership and job clusters. Where there are very few jobs, there is also very little bus ridership (and likely no routes at all).\n\n#### Step 18: Road data\n\nThat makes me wonder, what if a cell has no road. That will affect the ridership in a cell.\n\nAs there can't be bus stops where there are no roads, let's load a local road shapefile and identify any cells that have no roads in them\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let's map the roads\nggplot() +\n  geom_sf(data = roads, color = \"grey50\", linewidth = 0.2) +\n  theme_void() +\n  labs(title = \"Philadelphia Local Roads\")\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nThe roads clearly fill in almost all of the city. Most cells will have a road in them.\n\n#### Step 19: Creating a binary roads\n\nFor each cell, we'll create a binary variable that indicates whether it has a road in it or not There are 893 cells without roads in Philadelphia.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make a road_indicator that determines whether or not a cell has a road in it\n\nroad_indicator <- philly_grid %>%\n  mutate(has_road = as.integer(lengths(st_intersects(., roads)) > 0)) %>%\n  st_drop_geometry() %>%\n  select(cell_id, has_road)\n\ntable(road_indicator$has_road, useNA = \"ifany\") # we'll join this to the main grid later\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 \n 893 3334 \n```\n\n\n:::\n:::\n\n\n#### Step 20: Join categorical variable for roads to your final dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly_grid_final <- philly_grid_final %>%\n  left_join(road_indicator, by = \"cell_id\") %>%\n  mutate(has_road = replace_na(has_road, 0))\n\n#Checking if it worked\ntable(philly_grid_final$has_road, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1 \n 507 3154 \n```\n\n\n:::\n\n```{.r .cell-code}\n#Making a dataset for road length in each grid cell\nroad_length <- st_intersection(philly_grid, roads) %>%\n  mutate(length = st_length(geometry)) %>%\n  st_drop_geometry() %>%\n  group_by(cell_id) %>%\n  summarise(road_length = sum(length))\n```\n:::\n\n\n#### Step 21: Mapping which grid cells have roads\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd3 <- ggplot(philly_grid_final) +\n  geom_sf(aes(fill = factor(has_road)), color = NA) +\n  scale_fill_manual(values = c(\"0\" = \"darkgrey\", \"1\" = \"darkblue\")) +\n  theme_void() +\n  labs(title = \"Road Presence by Grid Cell\")\n\nd3\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/visualising the roads on grid cells-1.png){width=672}\n:::\n:::\n\n\n## Phase 2: Spatial Testing and Baselines\n\n#### Step 21: How will models work if there are NAs in the data?\n\nLet's check our data to make sure we're free of NAs in our predictors or dependent variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphilly_grid_final %>%\n  st_drop_geometry() %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  cell_id total_popE poverty_countE poverty_denomE no_vehicle_hhE total_hhE\n1       0          0              0              0              0         0\n  whiteE blackE hispanicE asianE median_income cell_area_km2 pop_density\n1      0      0         0      0             0             0           0\n  pct_no_vehicle pct_poverty pct_white pct_black pct_hispanic pct_asian\n1             53          14         0         0            0         0\n  total_riders unique_stops unique_routes dist_reg_rail_ft dist_el_ft\n1            0            0             0                0          0\n  jobs_half_mile has_road\n1              0        0\n```\n\n\n:::\n\n```{.r .cell-code}\n#Looks like we have some NAs in pct_no_vehicle and pct_poverty. \n#That's likely due to dividing by 0. \n#Let's fix that. \n#Let's just replace those with zeros since cells with no households can't have household poverty or car ownership\n\nphilly_grid_final <- philly_grid_final %>%\n  mutate(\n    pct_no_vehicle = ifelse(is.na(pct_no_vehicle) | is.nan(pct_no_vehicle), 0, pct_no_vehicle),\n    pct_poverty = ifelse(is.na(pct_poverty) | is.nan(pct_poverty), 0, pct_poverty)\n  )\n```\n:::\n\n\n#### Step 22: I want to see if there is spatial correlation. Let's check it using Moran's I and LISA Clustering\n\nWe will calculating the Moran's I Calucation for the total riders\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create neighbors\nnb <- poly2nb(philly_grid_final)\nlw <- nb2listw(nb, style = \"W\")\n\n#Run Local Moran's I\nlocal_moran <- localmoran(log1p(philly_grid_final$total_riders), lw) #Using log value for total riders as it is highly skewed\n\n#Add results back to philly_grid_final\nphilly_grid_final <- philly_grid_final %>%\n  mutate(\n    Ii = local_moran[,1],\n    p_value = local_moran[,5]\n  )\n\n#Create cluster labels\nphilly_grid_final <- philly_grid_final %>%\n  mutate(\n    moran_class = case_when(\n      total_riders > mean(total_riders) & Ii > 0 & p_value < 0.05 ~ \"High-High\",\n      total_riders < mean(total_riders) & Ii > 0 & p_value < 0.05 ~ \"Low-Low\",\n      total_riders > mean(total_riders) & Ii < 0 & p_value < 0.05 ~ \"High-Low\",\n      total_riders < mean(total_riders) & Ii < 0 & p_value < 0.05 ~ \"Low-High\",\n      TRUE ~ \"Not Significant\"\n    )\n  )\n```\n:::\n\n\n#### Step 23: LISA Cluster Map\n\nNow that we have the local cluster map through Moran's I, let's see how it looks!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualization for LISA\nggplot(philly_grid_final) +\n  geom_sf(aes(fill = moran_class), color = NA) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"red\",\n      \"Low-Low\" = \"blue\",\n      \"High-Low\" = \"orange\",\n      \"Low-High\" = \"lightblue\",\n      \"Not Significant\" = \"grey80\",\n      \"No Road\" = \"black\"\n    )\n  ) +\n  labs(\n    title = \"Local Moran’s I Cluster Map (Bus Ridership)\",\n    fill = \"Cluster Type\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/Mapping morans i to create the local cluster map-1.png){width=672}\n:::\n:::\n\n\n#### Step 24: It's time to prepare the variables for the models\n\n**Dependent variable** total_riders (or log-transformed)\n\n**Predictors** Demographics → population, income, etc. Jobs with 1/2 mile - jobs_half_mile Transit supply - unique_routes, stop_count Spatial - density variables Hotspots - Moran’s I classification\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Ridership is skewed so we are creating log transformed variable\nmodel_data <- philly_grid_final %>%\n  st_drop_geometry() %>%\n  mutate(\n    log_riders = log1p(total_riders),\n\n    # Convert categorical variables\n    moran_class = as.factor(moran_class)\n  ) %>%\n  drop_na(log_riders)\n```\n:::\n\n\n## Phase 3: Model Creation\n\n### Baseline OLS\n\n#### Step 25: I like OLS! Probably not the best model but the OLS Model should be a great baseline!\n\nLet's finally get into making models!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#OLS Regression Model\nmodel_ols <- lm(\n  log_riders ~ total_popE + jobs_half_mile +\n    unique_routes + unique_stops +\n    median_income,\n  data = model_data\n)\n\nsummary(model_ols)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_riders ~ total_popE + jobs_half_mile + unique_routes + \n    unique_stops + median_income, data = model_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.4560 -0.9054 -0.3607  1.0128  4.7314 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     1.054e+00  7.816e-02  13.490   <2e-16 ***\ntotal_popE      1.404e-03  8.279e-05  16.961   <2e-16 ***\njobs_half_mile -2.008e-05  2.258e-06  -8.892   <2e-16 ***\nunique_routes   7.431e-01  2.536e-02  29.300   <2e-16 ***\nunique_stops    6.598e-01  1.551e-02  42.534   <2e-16 ***\nmedian_income  -7.770e-06  8.270e-07  -9.396   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.48 on 3655 degrees of freedom\nMultiple R-squared:  0.7876,\tAdjusted R-squared:  0.7873 \nF-statistic:  2711 on 5 and 3655 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n#### Step 26: I want to see how the model performs during K-Fold Cross-Validation for OLS\n\nFor our cross validation we will be using the K-fold method As we analysis data post COVID which restricts the data on which we can test :(\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Cross Validation using K-folds method\n\nset.seed(123)\n\n# Split rows into 5 folds\nfolds <- createFolds(model_data$log_riders, k = 5)\n\n# Empty containers for each fold's score\nrmse_list <- c()\nmae_list  <- c()\nr2_list   <- c()\n\n# Loop through each of the 5 folds\nfor (i in 1:5) {\n  \n  test_rows <- folds[[i]]\n  train_set <- model_data[-test_rows, ]\n  test_set  <- model_data[ test_rows, ]\n  \n  # Fit the model on training data\n  fit <- lm(\n    log_riders ~ total_popE + jobs_half_mile +\n      unique_routes + unique_stops +\n      median_income,\n    data = train_set\n  )\n  \n  # Predict on test data, then back-transform from log to riders\n  pred_log    <- predict(fit, newdata = test_set)\n  pred_riders <- expm1(pred_log)\n  actual      <- test_set$total_riders\n  \n  # Calculate metrics in rider units\n  rmse_list[i] <- sqrt(mean((actual - pred_riders)^2))\n  mae_list[i]  <- mean(abs(actual - pred_riders))\n  r2_list[i]   <- cor(actual, pred_riders)^2\n}\n\n# Per-fold table\ndata.frame(\n  Fold = 1:5,\n  RMSE = round(rmse_list, 1),\n  MAE  = round(mae_list, 1),\n  R2   = round(r2_list, 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold      RMSE      MAE    R2\n1    1   67196.8   5458.3 0.171\n2    2  275206.4  20705.6 0.092\n3    3 6102279.5 249972.5 0.234\n4    4   90411.7   7749.1 0.089\n5    5  223997.2  17776.3 0.197\n```\n\n\n:::\n\n```{.r .cell-code}\n# Final averaged scores\ncat(\"Average RMSE:\", round(mean(rmse_list), 1), \"riders\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE: 1351818 riders\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average MAE: \", round(mean(mae_list), 1), \"riders\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage MAE:  60332.4 riders\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average R²:  \", round(mean(r2_list), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage R²:   0.157 \n```\n\n\n:::\n:::\n\n\n### Poisson Regression\n\n-   Designed for count data We are going to try both Poisson and Negative Binomial as they suit count data. Though we have some reservations as Poisson is almost certainly the wrong because it assumes mean ≈ variance, and our data won't satisfy that.\n\nTest is best way to be sure!\n\n#### Step 27: Time to make a Poisson Model for testing\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Making the Poisson Model\nlibrary(MASS)\n\nmean(model_data$total_riders)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 615.0276\n```\n\n\n:::\n\n```{.r .cell-code}\nvar(model_data$total_riders)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2562415\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_pois <- glm(\n  total_riders ~ total_popE + jobs_half_mile +\n    unique_routes + pct_no_vehicle + dist_el_ft + has_road +\n    median_income,\n  family = poisson(link = \"log\"),\n  data = model_data\n)\n\n# Predictions (response scale, not log)\npred_pois <- predict(model_pois, type = \"response\")\n\n# Actual values\nactual <- model_data$total_riders\n\n# RMSE\nrmse_pois <- sqrt(mean((actual - pred_pois)^2, na.rm = TRUE))\n\n# MAE\nmae_pois <- mean(abs(actual - pred_pois), na.rm = TRUE)\n\n# Print results\nrmse_pois\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1351.76\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_pois\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 505.6936\n```\n\n\n:::\n\n```{.r .cell-code}\n#Checking the summary for Poisson Model\nsummary(model_pois)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = total_riders ~ total_popE + jobs_half_mile + unique_routes + \n    pct_no_vehicle + dist_el_ft + has_road + median_income, family = poisson(link = \"log\"), \n    data = model_data)\n\nCoefficients:\n                 Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     4.601e+00  6.960e-03  661.13   <2e-16 ***\ntotal_popE      9.679e-04  1.987e-06  487.19   <2e-16 ***\njobs_half_mile -1.084e-05  3.225e-08 -335.99   <2e-16 ***\nunique_routes   3.867e-01  2.654e-04 1457.08   <2e-16 ***\npct_no_vehicle  3.394e-01  6.624e-03   51.23   <2e-16 ***\ndist_el_ft     -3.516e-05  1.270e-07 -276.81   <2e-16 ***\nhas_road        1.015e+00  5.860e-03  173.24   <2e-16 ***\nmedian_income  -3.548e-06  3.066e-08 -115.72   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 6651008  on 3660  degrees of freedom\nResidual deviance: 2576661  on 3653  degrees of freedom\nAIC: 2592013\n\nNumber of Fisher Scoring iterations: 7\n```\n\n\n:::\n:::\n\n\n### Negative Binomial Regression\n\n-   Designed for count data\n-   Handles overdispersion\n-   More realistic for transit demand\n\nWe tested Poisson, it's overdispersed and that's why we are moving to Negative Binomial. This seems the best method for non-spatial model for your data.\n\n#### Step 28: N.B Prediction Model for Ridership\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Making the Negative Binomial Model\nmodel_nb <- glm.nb(\n  total_riders ~ total_popE + jobs_half_mile +\n    unique_routes + pct_no_vehicle + dist_el_ft + has_road +\n    median_income,\n  data = model_data\n)\n\n#Comparing the Poisson and Negative Binomial Model\nAIC(model_nb, model_pois)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           df     AIC\nmodel_nb    9 2590722\nmodel_pois  8 2592013\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(coef(model_nb))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   (Intercept)     total_popE jobs_half_mile  unique_routes pct_no_vehicle \n    99.5391956      1.0009681      0.9999892      1.4724452      1.4043845 \n    dist_el_ft       has_road  median_income \n     0.9999648      2.7609498      0.9999964 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Predictions (response scale, not log)\npred_nb   <- predict(model_nb, type = \"response\")\n\n# Actual values\nactual <- model_data$total_riders\n\n# RMSE\nrmse_nb <- sqrt(mean((actual - pred_nb)^2, na.rm = TRUE))\n\n# MAE\nmae_nb <- mean(abs(actual - pred_nb), na.rm = TRUE)\n\n# Print results\nrmse_nb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1352.953\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_nb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 505.7514\n```\n\n\n:::\n:::\n\n\n#### Step 29: N.B model is still not doing great so I want to compare it with Poisson and find what's the problem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Compare NB vs Poisson to see if AIC is similar, NB isn't earning its place\nAIC(model_nb, model_pois)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           df     AIC\nmodel_nb    9 2590722\nmodel_pois  8 2592013\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Check for multicollinearity among predictors\ncar::vif(lm(total_riders ~ total_popE + jobs_half_mile + unique_routes +\n              pct_no_vehicle + dist_el_ft + has_road + median_income,\n            data = model_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    total_popE jobs_half_mile  unique_routes pct_no_vehicle     dist_el_ft \n      1.753739       1.468990       1.366123       2.414427       1.817132 \n      has_road  median_income \n      1.234433       1.521183 \n```\n\n\n:::\n\n```{.r .cell-code}\n# 3. Look at observed vs fitted (should be roughly aligned)\nplot(model_data$total_riders, fitted(model_nb),\n     xlab = \"Actual riders\", ylab = \"Predicted riders\")\nabline(0, 1, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/Negative Binomial Model-1.png){width=672}\n:::\n:::\n\n\n#### Step 30: The dispersion parameter for the previous model is extremely high!\n\nBased on the plot of actual vs predicted riders, the previous model under-predicting peaks, over-predicting some low cells which is a classic sign of missing predictors or wrong functional form, not bad statistics.\n\nThe model is using its limited features to extrapolate, and missing the structure that actually drives high-ridership cells\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_nb2 <- glm.nb(\n  total_riders ~ log1p(total_popE) + log1p(jobs_half_mile) +\n    pct_no_vehicle + dist_el_ft + has_road + median_income,           # add this — see below\n  data = model_data\n)\n\nAIC(model_nb, model_nb2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          df        AIC\nmodel_nb   9 2590722.12\nmodel_nb2  8   36412.22\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(coef(model_nb))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   (Intercept)     total_popE jobs_half_mile  unique_routes pct_no_vehicle \n    99.5391956      1.0009681      0.9999892      1.4724452      1.4043845 \n    dist_el_ft       has_road  median_income \n     0.9999648      2.7609498      0.9999964 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Predictions (response scale, not log)\npred_nb2   <- predict(model_nb2, type = \"response\")\n\n# RMSE\nrmse_nb2 <- sqrt(mean((actual - pred_nb2)^2, na.rm = TRUE))\n\n# MAE\nmae_nb2 <- mean(abs(actual - pred_nb2), na.rm = TRUE)\n\n# Print results\nrmse_nb2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1879.606\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_nb2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 792.5067\n```\n\n\n:::\n\n```{.r .cell-code}\n#Checking the summary for Negative Binomial Model\nsummary(model_nb2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = total_riders ~ log1p(total_popE) + log1p(jobs_half_mile) + \n    pct_no_vehicle + dist_el_ft + has_road + median_income, data = model_data, \n    init.theta = 0.1272238487, link = log)\n\nCoefficients:\n                        Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           -2.235e+00  4.261e-01  -5.245 1.57e-07 ***\nlog1p(total_popE)      4.993e-01  4.548e-02  10.977  < 2e-16 ***\nlog1p(jobs_half_mile)  6.325e-01  5.280e-02  11.981  < 2e-16 ***\npct_no_vehicle         6.631e-02  4.703e-01   0.141    0.888    \ndist_el_ft            -4.009e-05  5.279e-06  -7.594 3.10e-14 ***\nhas_road               1.229e+00  1.653e-01   7.436 1.04e-13 ***\nmedian_income         -1.667e-06  1.790e-06  -0.931    0.352    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(0.1272) family taken to be 1)\n\n    Null deviance: 4315.4  on 3660  degrees of freedom\nResidual deviance: 3541.0  on 3654  degrees of freedom\nAIC: 36412\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  0.12722 \n          Std. Err.:  0.00322 \nWarning while fitting theta: alternation limit reached \n\n 2 x log-likelihood:  -36396.21500 \n```\n\n\n:::\n:::\n\n\n**Our RMSE-to-MAE ratio is now about 2.4×, which is a healthy spread for count data. If we compare to my ratio for OLS, i.e 22×, this is god tier! This also confirms that ratio difference confirms the wild-outlier prediction problem is fixed.**\n\n#### Step 31: The model is still not explaining enough variance neither is it reducing the error !\n\nThe a big predictor missing is distance from center of the city Let's try it out\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add CBD distance (you skipped this before)\ncity_hall <- st_sfc(st_point(c(-75.1635, 39.9526)), crs = 4326) %>%\n  st_transform(2272)\n\nphilly_grid_final$dist_cbd_ft <- as.numeric(\n  st_distance(st_centroid(philly_grid_final), city_hall)\n)\n\nmodel_data <- model_data %>%\n  left_join(\n    philly_grid_final %>% st_drop_geometry() %>% \n      dplyr::select(cell_id, dist_cbd_ft),\n    by = \"cell_id\"\n  )\n\n# Clean any remaining NAs first\nmodel_data <- model_data %>%\n  mutate(\n    median_income = ifelse(is.na(median_income), \n                           median(median_income, na.rm = TRUE), \n                           median_income),\n    dist_cbd_ft   = ifelse(is.na(dist_cbd_ft), \n                           median(dist_cbd_ft, na.rm = TRUE), \n                           dist_cbd_ft)\n  )\n\n# Re-fit with CBD distance + a road-length term + population density\nmodel_nb3 <- glm.nb(\n  total_riders ~ log1p(total_popE) + log1p(jobs_half_mile) +\n    pct_no_vehicle + dist_el_ft + has_road + median_income +\n    log1p(dist_cbd_ft),\n  data = model_data,\n  control = glm.control(maxit = 200)\n)\n\nsummary(model_nb3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = total_riders ~ log1p(total_popE) + log1p(jobs_half_mile) + \n    pct_no_vehicle + dist_el_ft + has_road + median_income + \n    log1p(dist_cbd_ft), data = model_data, control = glm.control(maxit = 200), \n    init.theta = 0.1272599013, link = log)\n\nCoefficients:\n                        Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           -3.970e+00  1.702e+00  -2.333   0.0197 *  \nlog1p(total_popE)      4.956e-01  4.559e-02  10.871  < 2e-16 ***\nlog1p(jobs_half_mile)  6.590e-01  5.775e-02  11.412  < 2e-16 ***\npct_no_vehicle         3.265e-01  5.476e-01   0.596   0.5509    \ndist_el_ft            -4.465e-05  6.689e-06  -6.674 2.48e-11 ***\nhas_road               1.211e+00  1.663e-01   7.279 3.35e-13 ***\nmedian_income         -7.928e-07  2.117e-06  -0.374   0.7081    \nlog1p(dist_cbd_ft)     1.476e-01  1.384e-01   1.067   0.2860    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(0.1273) family taken to be 1)\n\n    Null deviance: 4316.5  on 3660  degrees of freedom\nResidual deviance: 3541.0  on 3653  degrees of freedom\nAIC: 36413\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  0.12726 \n          Std. Err.:  0.00322 \n\n 2 x log-likelihood:  -36395.23900 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Check whether it actually beats naive now\npred_nb3 <- predict(model_nb3, type = \"response\")\nrmse_nb3 <- sqrt(mean((model_data$total_riders - pred_nb3)^2))\nmae_nb3  <- mean(abs(model_data$total_riders - pred_nb3))\nr2_nb3   <- cor(model_data$total_riders, pred_nb3)^2\n\n#Print findings for nb3\n\nrmse_nb3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1794.991\n```\n\n\n:::\n\n```{.r .cell-code}\nmae_nb3 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 774.6579\n```\n\n\n:::\n\n```{.r .cell-code}\nr2_nb3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2061823\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"NB3 RMSE:\", round(rmse_nb3,0), \n    \" | improvement vs naive:\", round((1601 - rmse_nb3)/1601*100, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNB3 RMSE: 1795  | improvement vs naive: -12.1 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"NB3 MAE: \", round(mae_nb3,0), \n    \" | improvement vs naive:\", round((815  - mae_nb3) /815 *100, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNB3 MAE:  775  | improvement vs naive: 4.9 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"NB3 R²:  \", round(r2_nb3, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNB3 R²:   0.206 \n```\n\n\n:::\n:::\n\n\nAdding distance to City Center helped our model a little, but still not enough.\n\nWe'll have to get more data -- We've decided to get the locations of education and healthcare buildings, then create a \"distance to\" variable for them\n\n#### Step 32: Get University and Hospital building locations\n\nTo make the file smaller and easier to work with, we went ahead and filtered the land use geojson from opendataphilly to be just education and health care. That way, it can all be uploaded to github together without LFS issues.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `univ_hospital' from data source \n  `D:\\Ph.D\\US Pakistan Knowledge Corridore\\Upenn\\Subjects\\Public Policy Analytics\\Public-Policy-Analytics\\lab_6\\Data\\univ_hospital.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 83 features and 11 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.23003 ymin: 39.92048 xmax: -75.10809 ymax: 40.04241\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n#### Step 33: Create distance_to education and healthcare, and join to data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# split into separate layers\neducation <- univ_hospital %>% filter(c_dig3 == \"413\")\nhealthcare <- univ_hospital %>% filter(c_dig3 == \"411\")\n\neducation_centroids <- st_centroid(education)\nhealthcare_centroids <- st_centroid(healthcare)\n\n# Map them together to see where they are\nggplot() +\n  geom_sf(data = philly_grid_final, fill = \"grey95\", color = \"grey80\", linewidth = 0.1) +\n  geom_sf(data = education_centroids, aes(color = \"Education\"), size = 0.8, alpha = 0.6) +\n  geom_sf(data = healthcare_centroids, aes(color = \"Healthcare\"), size = 0.8, alpha = 0.6) +\n  scale_color_manual(\n    values = c(\"Education\" = \"steelblue\", \"Healthcare\" = \"firebrick\"),\n    name = \"Land Use\"\n  ) +\n  labs(\n    title = \"Education and Healthcare Buildings in Philadelphia\",\n    caption = \"Source: OpenDataPhilly Land Use dataset (codes 411, 413)\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/create distance_to variables for land uses-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Calculate distance to nearest education parcel\ndist_educ <- st_distance(grid_centroids, education_centroids)\nphilly_grid_final$dist_education_ft <- apply(dist_educ, 1, min)\n\n# Calculate distance to nearest healthcare parcel\ndist_health <- st_distance(grid_centroids, healthcare_centroids)\nphilly_grid_final$dist_healthcare_ft <- apply(dist_health, 1, min)\n\n# Join to model_data\nmodel_data <- model_data %>%\n  left_join(\n    philly_grid_final %>% \n      st_drop_geometry() %>%\n      dplyr::select(cell_id, dist_education_ft, dist_healthcare_ft),\n    by = \"cell_id\"\n  )\n```\n:::\n\n\n### Final Model (NB4)\n\n#### Step 34: Fitting a new NB model\n\nIn the last model (nb3), pct_no_vehicle and median_income came out as not significant predictors. In this next model, we'll remove them and see if our predictive ability improves.\n\nAlso, let's add those distance to education and healthcare buildings in!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_nb4 <- glm.nb(\n  total_riders ~ log1p(total_popE) + log1p(jobs_half_mile) +\n    dist_el_ft + has_road + \n    log1p(dist_cbd_ft) + log1p(dist_education_ft) + log1p(dist_healthcare_ft),\n  data = model_data,\n  control = glm.control(maxit = 200)\n)\n\nsummary(model_nb4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = total_riders ~ log1p(total_popE) + log1p(jobs_half_mile) + \n    dist_el_ft + has_road + log1p(dist_cbd_ft) + log1p(dist_education_ft) + \n    log1p(dist_healthcare_ft), data = model_data, control = glm.control(maxit = 200), \n    init.theta = 0.1285416854, link = log)\n\nCoefficients:\n                            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)               -4.553e+00  1.351e+00  -3.371 0.000748 ***\nlog1p(total_popE)          4.956e-01  4.531e-02  10.938  < 2e-16 ***\nlog1p(jobs_half_mile)      7.361e-01  5.873e-02  12.534  < 2e-16 ***\ndist_el_ft                -2.910e-05  7.161e-06  -4.063 4.83e-05 ***\nhas_road                   1.256e+00  1.667e-01   7.537 4.81e-14 ***\nlog1p(dist_cbd_ft)         5.303e-01  1.290e-01   4.111 3.95e-05 ***\nlog1p(dist_education_ft)  -2.597e-01  1.309e-01  -1.983 0.047370 *  \nlog1p(dist_healthcare_ft) -1.954e-01  1.404e-01  -1.393 0.163764    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(0.1285) family taken to be 1)\n\n    Null deviance: 4355.7  on 3660  degrees of freedom\nResidual deviance: 3540.2  on 3653  degrees of freedom\nAIC: 36381\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  0.12854 \n          Std. Err.:  0.00325 \n\n 2 x log-likelihood:  -36363.30100 \n```\n\n\n:::\n\n```{.r .cell-code}\npred_nb4 <- predict(model_nb4, type = \"response\")\nrmse_nb4 <- sqrt(mean((model_data$total_riders - pred_nb4)^2))\nmae_nb4  <- mean(abs(model_data$total_riders - pred_nb4))\nr2_nb4   <- cor(model_data$total_riders, pred_nb4)^2\n\ncat(\"NB4 RMSE:\", round(rmse_nb4, 0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNB4 RMSE: 1586 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"NB4 MAE: \", round(mae_nb4, 0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNB4 MAE:  737 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"NB4 R²:  \", round(r2_nb4, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNB4 R²:   0.174 \n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(model_nb, model_nb2, model_nb3, model_nb4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          df        AIC\nmodel_nb   9 2590722.12\nmodel_nb2  8   36412.22\nmodel_nb3  9   36413.24\nmodel_nb4  9   36381.30\n```\n\n\n:::\n:::\n\n\nThe nb4 is the best model we've made so far, with the lowest RMSE and MAE we've seen (1586 and 737 respectively). Also, its AIC is better (lower) than previous models, suggesting it's the most effective one so far.\n\nNow, let's run a leave-one-out cross validation! We're only showing the LOOCV for this specific model since it has our best up front diagnostics, and the LOOCV takes a long time to run on our RStudio. If you want, you can run this same LOOCV code on the other models to see for yourself!\n\n#### Step 35: LOOCV for our NB4 model... or at least try...\n\n\n::: {.cell}\n\n```{.loocv .cell-code}\n# \n# library(MASS)\n# \n# # Store actual values\n# actual <- model_data$total_riders\n# n <- nrow(model_data)\n# \n# # Empty containers\n# loocv_pred <- numeric(n)\n# \n# for (i in 1:n) {\n#   \n#   # Split into train and test\n#   train_set <- model_data[-i, ]\n#   test_obs  <- model_data[i, ]\n#   \n#   # Fit NB4 on all rows except i\n#   fit <- glm.nb(\n#     total_riders ~ log1p(total_popE) + log1p(jobs_half_mile) +\n#       pct_no_vehicle + dist_el_ft + has_road + median_income +\n#       log1p(dist_cbd_ft) + log1p(dist_education_ft) + log1p(dist_healthcare_ft),\n#     data = train_set,\n#     control = glm.control(maxit = 200)\n#   )\n#   \n#   # Predict the held-out observation\n#   loocv_pred[i] <- predict(fit, newdata = test_obs, type = \"response\")\n# }\n# \n# # Calculate metrics\n# loocv_rmse <- sqrt(mean((actual - loocv_pred)^2))\n# loocv_mae  <- mean(abs(actual - loocv_pred))\n# loocv_r2   <- cor(actual, loocv_pred)^2\n# \n# cat(\"LOOCV RMSE:\", round(loocv_rmse, 0), \"\\n\")\n# cat(\"LOOCV MAE: \", round(loocv_mae, 0), \"\\n\")\n# cat(\"LOOCV R²:  \", round(loocv_r2, 3), \"\\n\")\n\n```\n:::\n\n\n**So, we've run into an issue.... :(**\n\nWe could not get the LOOCV even after running it and walking away to let it work for over an hour. After some troubleshooting, we found that it would take our computers hours to run the LOOCV.\n\nIn the sake of time savings due to computational restraints, we're going to swap to a 10-fold cross-validation. The LOOCV would mean re-fitting the model on all 3,600+ grid cells.\n\n10-fold cross-validation offers a more stable estimate of generalization error than LOOCV in datasets with high-ridership outlier cells, which we still have a few of even after filtering out cells with 25,000+ ridership.\n\nSo, let's run the 10-fold!\n\n#### Step 36: 10-fold Cross Validation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\nk <- 10\nfolds <- createFolds(model_data$total_riders, k = k)\n\nloocv_rmse <- c()\nloocv_mae  <- c()\nloocv_r2   <- c()\n\nfor (i in 1:k) {\n  test_rows <- folds[[i]]\n  train_set <- model_data[-test_rows, ]\n  test_set  <- model_data[test_rows, ]\n  \n  fit <- glm.nb(\n    total_riders ~ log1p(total_popE) + log1p(jobs_half_mile) +\n      pct_no_vehicle + dist_el_ft + has_road + median_income +\n      log1p(dist_cbd_ft) + log1p(dist_education_ft) + log1p(dist_healthcare_ft),\n    data = train_set,\n    control = glm.control(maxit = 200)\n  )\n  \n  pred  <- predict(fit, newdata = test_set, type = \"response\")\n  actual <- test_set$total_riders\n  \n  loocv_rmse[i] <- sqrt(mean((actual - pred)^2))\n  loocv_mae[i]  <- mean(abs(actual - pred))\n  loocv_r2[i]   <- cor(actual, pred)^2\n}\n\ndata.frame(\n  Fold = 1:k,\n  RMSE = round(loocv_rmse, 1),\n  MAE  = round(loocv_mae, 1),\n  R2   = round(loocv_r2, 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Fold   RMSE   MAE    R2\n1     1 1417.5 732.7 0.063\n2     2 1737.9 820.8 0.259\n3     3 1142.5 609.8 0.307\n4     4 1867.2 800.5 0.087\n5     5 1859.7 813.1 0.173\n6     6 1836.6 833.2 0.132\n7     7 1482.6 767.6 0.132\n8     8 1687.4 751.6 0.207\n9     9 1814.2 752.3 0.257\n10   10 1446.8 744.2 0.034\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average RMSE:\", round(mean(loocv_rmse), 0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage RMSE: 1629 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average MAE: \", round(mean(loocv_mae), 0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage MAE:  763 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Average R²:  \", round(mean(loocv_r2), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage R²:   0.165 \n```\n\n\n:::\n:::\n\n\nAfter running our cross-validation, we get a final RMSE of 1629, an MAE of 763, and an average R\\^2 of 0.165.\n\nThe R\\^2 is quite low, only explaining 16.5% of the variance in ridership by cell. That being said, ridership varies massively cell to cell.\n\nLet's map our errors and see where our model seems to be struggling the most:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add predictions and residuals back to the spatial grid\nphilly_grid_final <- philly_grid_final %>%\n  left_join(\n    model_data %>% \n      dplyr::select(cell_id, total_riders) %>%\n      mutate(\n        predicted_nb4 = predict(model_nb4, newdata = model_data, type = \"response\"),\n        residual      = total_riders - predicted_nb4,\n        abs_error     = abs(residual)\n      ),\n    by = \"cell_id\"\n  )\n\n# Map absolute error\ne1 <- ggplot(philly_grid_final) +\n  geom_sf(aes(fill = abs_error), color = NA) +\n  scale_fill_viridis_c(\n    option = \"magma\",\n    name = \"Absolute Error\\n(riders)\",\n    limits = c(0, 5000),\n    oob = scales::squish\n  ) +\n  labs(\n    title = \"Model Error by Grid Cell\",\n    subtitle = \"NB4 — Absolute difference between predicted and actual riders\",\n    caption = \"Scale capped at 5,000 riders. Cells exceeding cap shown in yellow.\"\n  ) +\n  theme_void()\n\n# Map signed residuals to see over/underprediction\ne2 <- ggplot(philly_grid_final) +\n  geom_sf(aes(fill = residual), color = NA) +\n  scale_fill_gradient2(\n    low = \"blue\", mid = \"white\", high = \"red\", midpoint = 0,\n    name = \"Residual\\n(riders)\",\n    limits = c(-5000, 5000),\n    oob = scales::squish\n  ) +\n  labs(\n    title = \"Over vs. Underprediction by Grid Cell\",\n    subtitle = \"Red = model underpredicts | Blue = model overpredicts\",\n    caption = \"Scale capped at ±5,000 riders.\"\n  ) +\n  theme_void()\n\ne1 + e2\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/map the errors of nb4 model-1.png){width=672}\n:::\n:::\n\n\nOur highest errors occur downtown, where we mostly underpredict ridership save a few spots in the center of CC where we overpredict. In the least dense parts of the city, nb4 has much lower errors, granted those areas have low ridership in the first place. The pattern of overpredictions are small, single or 1-3 cell clusers of very high overpredictions, with fast dropoffs in the cells around them. In our underpredictions, on the other hand, they're more spread in larger areas and even contain little spikes of overpredictions.\n\nOverall our nb4 model has the highest errors in Center City, University City, and in North Philly.\n\nThere's one map that has similar areas of the highest values as our absolute error map...\n\n\n::: {.cell}\n\n```{.r .cell-code}\np6 + e1\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nJobs within a half-mile and absolute error appear to occur in similar spots - mainly in CC and University City, spreading north in a relatively straight line.\n\n## Phase 4: Results\n\nLets take a look at the actual ridership values by cell next to our predicted ridership by cell:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# first, it looks like we accidentally made a total_riders.x and .y somewhere. Must've been a join somewhere that duplicated total_riders. Let's fix that real quick!\n\nphilly_grid_final <- philly_grid_final %>%\n   rename(total_riders = total_riders.x) %>%\n   dplyr::select(-total_riders.y)\n\n# Map actual vs predicted side by side\na1 <- ggplot(philly_grid_final) +\n  geom_sf(aes(fill = total_riders), color = NA) +\n  scale_fill_viridis_c(\n    option = \"magma\",\n    name = \"Actual Riders\",\n    limits = c(0, 10000),\n    oob = scales::squish\n  ) +\n  labs(\n    title = \"Actual Bus Ridership\",\n    subtitle = \"Observed ridership by grid cell\"\n  ) +\n  theme_void()\n\na2 <- ggplot(philly_grid_final) +\n  geom_sf(aes(fill = predicted_nb4), color = NA) +\n  scale_fill_viridis_c(\n    option = \"magma\",\n    name = \"Predicted Riders\",\n    limits = c(0, 10000),\n    oob = scales::squish\n  ) +\n  labs(\n    title = \"Predicted Bus Ridership\",\n    subtitle = \"NB4 model predictions by grid cell\"\n  ) +\n  theme_void()\n\na1 + a2\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/map actual and predicted ridership (nb4)-1.png){width=672}\n:::\n:::\n\n\nIn the side by side views of the actual ridership and the predicted ridership from our NB4 model, we can see that there are similar cluster of high ridership values in CC, north Philly, and South Philly. The model does a good job of predicting the low-ridership areas to be mostly low still.\n\nSpots where our model overpredicts could be locations where investment could be prioritized, because it means that the location has attributes that suggest high ridership, but currently has low ridership (likely due to lack of infrastructure). This is one of the functions of our model that we think SEPTA could use to find where to invest their resources best, getting the most out of their limited budget and capacity.\n\nLet's make a map of where our actal ridership vs. predicted ridership suggests areas of good investment:\n\n### Mapping predicted vs actual gaps and classifying by investment priority\n\nWhat better way then mapping the predicted ridership\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualization for predicted ridership\n\na2\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n### Investment Logic\n\nUsing our predicted ridership we will check where SEPTA would benefit the most from investing\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating a variable for where we can invest\n\nphilly_grid_final <- philly_grid_final %>%\n  mutate(\n    investment_priority = case_when(\n      predicted_nb4 > quantile(predicted_nb4, 0.8) ~ \"High Investment\",\n      predicted_nb4 < quantile(predicted_nb4, 0.2) ~ \"Low Priority\",\n      TRUE ~ \"Moderate\"\n    )\n  )\n\n#Creating a variable to see where we see major gaps in predicted vs current ridership\nphilly_grid_final <- philly_grid_final %>%\n  mutate(\n    gap = predicted_nb4 - total_riders\n  )\n```\n:::\n\n\n### How can the model be used? [Example]\n\nWe are excluding \"low priority\" from the map, because we want to promote transit growth, not cutting of essential service.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Creating a variable for where we can invest\n\nlibrary(scales)\n\nm2 <- ggplot(philly_grid_final) +\n  geom_sf(aes(fill = gap), color = NA) +\n  geom_sf(data = philadelphia, fill = NA, color = \"black\", linewidth = 0.1) +\n  scale_fill_gradient2(\n    mid = \"white\",\n    high = \"red\",\n    midpoint = 0,\n    name = \"Gap (Pred - Actual)\",\n    limits = c(0, 10000),\n    oob = scales::squish\n  ) +\n  theme_void() +\n  labs(title = \"Ridership Gap (Predicted - Actual)\")\n\n# map it!\nm2\n```\n\n::: {.cell-output-display}\n![](Final_Model_TechnicalAppendix_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nOn this map, we can see where our model predicts the greatest increase of ridership (based on predicted ridership - actual). This would help SEPTA make decisions about how they can focus their resources (monetary and capacity) in places where their investments would go further based on that area's characteristics.\n\n# Conclusion\n\n**Summary**\n\nWe embarked on this project with the goal of creating a tool to help SEPTA optimize resources and strengthen its public image. In the wake of constrained budgets and low organisational capacity in SEPTA our project uses demographic, spatial, and categorical data to predict SEPTA bus ridership across Philadelphia at an 1000x1000ft grid. \n\nWe created multiple models, and landed on a negative binomial model that works well in moderate ridership areas and holds the potential to be refined to predict ridership at more specific scopes in Philadelphia. \n\n**Model scope**\n\nBy excluding extremely high outlier ridership cells, we are limiting our scope of prediction slightly, but improving our predictive power substatntially. To predict ridership at transit hubs with very high ridership, a separate model would be more effective.\n\n**Limitations & Bias Considerations**\n\nModel is Anchored to Current Conditions\n\n-   Predictions reflect existing ridership under existing infrastructure\n-   A transit desert predicts low ridership — not because demand is absent, but because supply was never provided\n-   This risks reinforcing existing inequities in transit access\n    -   To avoid reinforcing current transit deserts, we have opted to exclude a spatial lag of ridership anywhere in our predictions, as to avoid the cyclical problem of predicting on current infrastructure.\n\n**Recommendations for Implementation** - How would the city use our model?\n\n-   The model can be used for analyzing and identifying areas with higher ridership to create investment strategies\n-   Simply use the model to predict future ridership to plan capacity building within SEPTA\n\n**Thank you for reading our report!**\n",
    "supporting": [
      "Final_Model_TechnicalAppendix_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}