project:
  type: website
  output-dir: docs

website:
  title: "UMAIR BIN SAADD - MUSA 50888880 Portfolio"
  navbar:
    left:
      - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_4/lab_4.html
        text: Home
      - text: Labs
        menu:
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_4/lab_4.html
            text: "cccccccccccc"
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_4/lab_4.html
            text: "zxczxczxccx"
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_4/lab_4.html
            text: "Lab 4: Spatial Analysis"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
