project:
  type: website
  output-dir: docs

website:
  title: "UMAIR BIN SAADD - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_4/lab_4.html
        text: Home
      - text: Labs
        menu:
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/Lab_0/lab0_template.html
            text: "Lab 0: Getting Started with dplyr"
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_1/lab1_template (1).html
            text: "Lab 1: Census Data Quality for Policy Decisions"
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_2/lab2_template.html
            text: "Lab 2: Spatial Analysis and Visualization"  
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_3/TechAppendix.html
            text: "Lab 3: Philadelphia Housing Price Prediction"  
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_4/lab_4.html
            text: "Lab 4: Spatial Predictive Analysis"
          - href: https://umairbinsaad.github.io/Public-Policy-Analytics/lab_5/lab_5.html
            text: "Lab 5: Bikeshare_SpaceTime_Prediction"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
